### ISSUE TITLE
CodeCoverage Tag is showing and duplicating

### ISSUE THREAD

**Issue by d1820** [rstedman/tfs-pullrequest-dashboard#48]
Since the release 2 days ago, a new tag (CodeCoverage) is showing on the Dashboard, and keeps duplicating. Im not sure what this tag is supposed to be showing or why it just now started showing on our projects?

![image](https://user-images.githubusercontent.com/377631/61889777-e889b600-aeba-11e9-95a7-873325650a58.png)

![image](https://user-images.githubusercontent.com/377631/61890317-0d325d80-aebc-11e9-9fd2-d3e7180f7538.png)

**Comment by rstedman** [comment]
I am not seeing this in my project, and I can't see how it could be related to the changes that were released this week.

When you have the dashboard open, could you open the chrome developer tools (or equivalent for your browser), switch to the network tab and refresh the page.  The dashboard will query azure devops for the statues (which are turned into tags) of each PR.  What do the responses of these requests look like for you? Are any of your PR statuses showing a large number of "codecoverage" statuses?  If so, something else is adding statuses to your PRs - possibly constantly adding new statuses instead of updating existing ones, and this extension is just displaying them.  ex:

![image](https://user-images.githubusercontent.com/5440997/61917838-00922180-af1d-11e9-99b2-7c0eb1c28f81.png)

**Comment by d1820** [comment]
Confirmed its in the statuses of the devops requests... Sorry for filing, and thank you for the response.. now to figure out what has changed there :)

**Comment by nertner** [comment]
The number of codecoverage badges seems excessive.  May I request changing it to a badge with number instead of a badge for every "statuses" response?  ex. [codecoverage (19)]

![image](https://user-images.githubusercontent.com/3586334/62304464-debfff80-b432-11e9-80e1-484cfa91ff86.png)
