### ISSUE TITLE
Authentication required popup

### ISSUE THREAD

**Issue by slandsaw** [rstedman/tfs-pullrequest-dashboard#6]
Installed this extension on TFS 2017 Update 3. Anytime I try to access the Pull Request Dashboard I am prompted for credentials. 

Opening developer tools in chrome shows me this: 

```
TF400813: Resource not available for anonymous access. Client authentication required.
type: Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException
isRemoteException: false
errorCode: 0
eventId: 3000
```

And in the developer tools console I see this also: 

```
ERROR Error: Uncaught (in promise): TFS.WebApi.Exception: TF400813: Resource not available for anonymous access. Client authentication required.
TFS.WebApi.Exception: TF400813: Resource not available for anonymous access. Client authentication required.
```

**Comment by rstedman** [comment]
Is your TFS instance set up to allow anonymous access?  Are you signed into TFS as a specific user?  When you are in TFS, do you see your user icon in the top right of the screen? ex:

![image](https://user-images.githubusercontent.com/5440997/34073776-93c81fb2-e26f-11e7-9188-66a7ea655f09.png)

This extension makes API calls to TFS for getting information about the user you are logged in as in order to categorize the pull requests.  If your tfs instance uses strictly anonymous access, I don't think that this extension will work for you.

**Comment by slandsaw** [comment]
1.) Anonymous and Windows auth is enabled
2.) Providers are Negotiate (Kerberos) and NTLM
3.) I have admin access to TFS
4.) I do see my user icon

Another custom extension (developed in-house) was also not loading. I used TfsConfig to switch the auth type to NTLM, but that had no impact on the issue.  Switched back to Negotiate and now the extensions are working as expected.

**Comment by rstedman** [comment]
Glad to hear you've resolved the issue.  

I've also fixed & published a new version for a very similar issue reported by another user, though their issue only occurred when checking the "All projects" setting.  It sounds like you won't be changing the auth settings on your TFS instance, since it also fixes your other extension, but if you ever need to, this new version may address the error you were seeing.
